name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        env:
          REPOSITORY_REF: ${{ github.event.pull_request.head.sha || github.sha }}
        with:
          category: integration
